version: '3.9'
services:
  marketplace:
    container_name: marketplace
    build: 
      context: .
      dockerfile: ./Dockerfile

# docker-compose up --build -d

# docker run --name apk-builder_bash --rm -i -t android_apk-builder bash

# docker system prune -a -f