version: '3'

services:
  jenkinsfile-runner:
    # image: jenkins/jenkinsfile-runner
    build:
      context: .
      dockerfile: ./Dockerfile.jenkins-test
    container_name: jenkinsfile-runner
    # command: sleep infinity
    # command: |
    #   # echo "me & you" \
    #   sleep infinity
    # command: tail -f /dev/null
    volumes:
      - ./:/build
      - ./Jenkinsfile.test:/build/Jenkinsfile
      - ./Jenkinsfile.test:/workspace/Jenkinsfile
    environment:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: true
      # - JAVA_OPTS="-Xms 256m"


# docker-compose up --build -d --force-recreate


# docker run --rm -e JAVA_OPTS="-Xms 256m" -v $PWD/test:/workspace jenkins/jenkinsfile-runner
# docker run --rm -v $(pwd)/Jenkinsfile:/workspace/Jenkinsfile jenkins/jenkinsfile-runner
