# name: trigger jenkins job

# on:
#   push:
#     branches: [main-]

# env:
#   JOB_NAME: 'mailing-ui'
#   TOKEN: '11047e72bfa202474b4d1b44354cb8de16'
# jobs:
#   build:
#     name: Notify Jenkins
#     runs-on: ubuntu-latest
#     steps:
#     - name: trigger multiple Job
#       uses: appleboy/jenkins-action@master
#       with:
#         # url: "https://jenkins.centralium.site"
#         url: "http://65.109.65.236:7000/"
#         user: "admin"
#         token: ${{ env.TOKEN }}
#         job: "${{ env.JOB_NAME }}"
