name: push-to-another-repo

on:
  push:
    branches: [main-]

env:
  TOKEN: 'IqI6yIgYXweCMtefMRDu'
jobs:
  # push-v2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Pushes to another repository
  #       uses: cpina/github-action-push-to-another-repository@main
  #       env:
  #         # SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
  #         API_TOKEN_GITHUB: ${{env.TOKEN}}
  #       with:
  #         source-directory: ./
  #         destination-github-username: mohamed-mourabit
  #         destination-repository-name: microfront
  #         user-email: mohamed-mourabit
  #         target-branch: main

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          github-server-url: 'https://djm2x@bitbucket.org'
          repository: mohamed-mourabit/microfront
          ref: 'dev'
          token: ${{env.TOKEN}}
      - name: setup git config
        run: |
          git config user.name "mohamed-mourabit"
          git config user.email "dj6m2x@gmail.com"
      # - <make changes and commit >
      - run: git push origin dev

